RTC and NTP time added
klicGdl/IrrigationSystem pull request #10
Opened 2022-09-01 18:06 UTC by Hugo-oz

2022-09-01 18:34 UTC, Elemeants requested changes

2022-09-01 18:34 UTC, Elemeants commented on src/system/time/services/ntp.cpp
> +    this->datetime = { 0, 0, 0, 0, 0, 0 };
This can be moved to `init` function

2022-09-01 18:34 UTC, Elemeants commented on src/system/time/services/ntp.cpp
> +NTPClient timeClient(ntpUDP);
Those variables should be attributes of the class, otherwise each class will reference the same variables.

2022-09-01 18:34 UTC, Elemeants commented on src/system/time/services/rtc.cpp
> +RTC_DS3231 rtc;
Same as Wifi file variables.

2022-09-01 18:34 UTC, Elemeants commented on src/system/time/services/rtc.cpp
> +        return true;
This code should be on the `update` function, so every time you want to update the time, you call the rtc.

2022-09-01 18:34 UTC, Elemeants commented on src/utils/time_converter.cpp
> +int year_zero = 1970;
This can be define.

2022-09-01 18:34 UTC, Elemeants commented on src/utils/time_converter.cpp
> +#define MINUTE 60
Rename this to reference a convertion, ex: `SECONDS_IN_YEAR`

2022-09-01 18:34 UTC, Elemeants commented on src/utils/time_converter.h
> +  datetime_t TimeConverter(unsigned long epoch);
Missing `@return` on comment.

2022-09-01 19:09 UTC, Elemeants commented on src/system/time/services/ntp.cpp
> +    datetime = TimeConverter(timeClient.getEpochTime());
This function should be called `getDateTimeFromEpochTime`

2022-09-01 19:10 UTC, Elemeants commented on src/system/time/services/rtc.cpp
> +    else{
This else is not necesary, since you are already returning if the rtc is not beginned.

2022-09-01 19:15 UTC, Elemeants commented on src/utils/time_converter.cpp
> +    datetime.year = year_zero+((int)(epoch/YEAR));
`datetime.year = (uint8_t) (year_zero + (epoch/YEAR));`

2022-09-01 19:28 UTC, Elemeants commented on src/system/time/services/ntp.cpp
> +WiFiUDP ntpUDP;
Why this variable?

2022-09-01 19:29 UTC, Elemeants commented on src/system/time/services/ntp.cpp
> +#include "utils/time_converter.cpp"
Don't include a .cpp file, you need to include the header

2022-09-01 19:33 UTC, Elemeants commented on src/system/time/services/ntp.cpp
> +    timeClient.begin();
Check if NTP was beginned?

2022-09-01 19:52 UTC, Elemeants commented on src/system/time/services/ntp.cpp
Those defines aren't needed, please remove them.

2022-09-19 21:37 UTC, Elemeants approved these changes

2022-09-19 21:38 UTC, Elemeants commented
Good job Hugo!
You're so quick!

2022-09-19 21:57 UTC, merged

2022-09-30 01:24 UTC, jpreciad commented
Hugo!!!! Thanks for your support to complete this task!